worker_heartbeat_timeout: 300000

num_workers: 1

logging:
  level: info

wiki: &wiki
<%- @wikis.each_pair do |wiki, value| -%>
<%- if value == true -%>
        - uri: 'https://<%= wiki %>.miraheze.org/w/api.php'
          domain: '<%= wiki %>.miraheze.org'
<%- else -%>
        - uri: 'https://<%= value %>/w/api.php'
          domain: '<%= value %>'
<%- end -%>
<%- end -%>

services:
  - module: /srv/parsoid/lib/index.js
    entrypoint: apiServiceWorker
    conf:
      mwApis: *wiki
      # /!\ COMPATIBILITY for Parsoid 0.9.0 with MediaWiki before 1.31
      strictAcceptCheck: false
      loadWMF: false
      debug: false
      usePHPPreProcessor: true
      useSelser: true
      linting: true
      linterSendAPI: false
      strictSSL: true
      useWorker: true
