# RESTBase config for small wiki installs
#
# - sqlite backend
# - parsoid at https://parsoid-lb.miraheze.org
# - wiki at https://<wiki>.miraheze.org/w/api.php or https://<custom_wiki>/w/api.php
# 
# Quick setup:
# - npm install
#   If you see errors about sqlite, you might have to `apt-get install
#   libsqlite3-dev`.
# - cp config.example.yaml config.yaml
# - double-check and possibly modify lines marked with XXX, then start restbase with
#
#   node server
#
# - If all went well, http://localhost:7231/localhost/v1/page/html/Main_Page
# should show your wiki's [[Main Page]].

num_workers: 2

default_project: &default_project
  x-modules:
    - path: /srv/restbase/projects/example.yaml
      options:
        action:
          apiUriTemplate: "{{'https://{domain}/w/api.php'}}"
          baseUriTemplate: "{{'https://{domain}/api/rest_v1'}}"
        parsoid:
          # XXX Check Parsoid URL!
          host: https://parsoid-lb.miraheze.org
          grace_ttl: 1
        table:
          backend: sqlite
          dbname: db.sqlite3
          pool_idle_timeout: 20000
          retry_delay: 250
          retry_limit: 10
          show_sql: false
        purged_cache_control: s-maxage=0, max-age=86400
        purged_cache_control_client_cache: s-maxage=0, max-age=300

services:
  - name: restbase
    module: hyperswitch
    conf: 
      port: 7231
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      ui_name: RESTBase
      ui_url: https://www.mediawiki.org/wiki/RESTBase
      ui_title: RESTBase docs
      spec:
        x-request-filters:
          - path: lib/security_response_header_filter.js
        x-sub-request-filters:
          - type: default
            name: http
            options:
            allow:
              - pattern: /^https?:\/\/[a-zA-Z0-9\.]+\/w\/api\.php/
                forward_headers: true
              - pattern: https://parsoid-lb.miraheze.org
                forward_headers: true
        paths:
<%- @wikis.each_pair do |wiki, value| -%>
<%- if value == true -%>
          /{domain:<%= wiki %>.miraheze.org}: *default_project
<%- else -%>
          /{domain:<%= value %>.miraheze.org}: *default_project
<%- end -%>
<%- end -%>

    # A robots.txt to make sure that the content isn't indexed.
    /robots.txt:
      get:
        x-request-handler:
          - static:
              return:
                status: 200
                headers:
                  content-type: text/plain
                body: |
                  User-agent: *
                  Allow: /*/v1/?doc
                  Disallow: /

# Finally, a standard service-runner config.
info:
  name: restbase

logging:
  name: restbase
  level: info
