# RESTBase config for small wiki installs
#
# - sqlite backend
# - parsoid at https://parsoid-lb.miraheze.org
# - wiki at https://<wiki>.miraheze.org/w/api.php or https://<custom_wiki>/w/api.php
# 
# Quick setup:
# - npm install
#   If you see errors about sqlite, you might have to `apt-get install
#   libsqlite3-dev`.
# - cp config.example.yaml config.yaml
# - double-check and possibly modify lines marked with XXX, then start restbase with
#
#   node server
#
# - If all went well, http://localhost:7231/localhost/v1/page/html/Main_Page
# should show your wiki's [[Main Page]].

services:
  - name: restbase
    module: hyperswitch
    conf: 
      port: 7231
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      ui_name: RESTBase
      ui_url: https://www.mediawiki.org/wiki/RESTBase
      ui_title: RESTBase docs
      spec:
        x-request-filters:
          - path: lib/security_response_header_filter.js
        x-sub-request-filters:
          - type: default
            name: https
            options:
            allow:
<%- @wikis.each_pair do |wiki, value| -%>
<%- if value == true -%>
              - pattern: https://<%= wiki %>.miraheze.org/w/api.php
                forward_headers: true
<%- else -%>
              - pattern: https://<%= value %>/w/api.php
                forward_headers: true
<%- end -%>
<%- end -%>
              - pattern: https://parsoid-lb.miraheze.org
                forward_headers: true
        paths:
<%- @wikis.each_pair do |wiki, value| -%>
<%- if value == true -%>
          /{domain:<%= wiki %>.miraheze.org}:
            x-modules:
              - path: /srv/restbase/restbase/projects/example.yaml
                options:
                  action:
                    # XXX Check API URL!
                    apiUriTemplate: https://<%= wiki %>.miraheze.org/w/api.php
                    # XXX Check the base RESTBase URI
                    baseUriTemplate: "{{'https://{domain}/api/rest_v1'}}"
                  parsoid:
                    # XXX Check Parsoid URL!
                    host: https://parsoid-lb.miraheze.org
                  table:
                    backend: sqlite
                    dbname: db.sqlite3
                    pool_idle_timeout: 20000
                    retry_delay: 250
                    retry_limit: 10
                    show_sql: false
                  purged_cache_control: s-maxage=0, max-age=86400
                  purged_cache_control_client_cache: s-maxage=0, max-age=300
<%- else -%>
          /{domain:<%= value %>}:
            x-modules:
              - path: /srv/restbase/restbase/projects/example.yaml
                options:
                  action:
                    # XXX Check API URL!
                    apiUriTemplate: https://<%= value %>/w/api.php
                    # XXX Check the base RESTBase URI
                    baseUriTemplate: "{{'https://{domain}/api/rest_v1'}}"
                  parsoid:
                    # XXX Check Parsoid URL!
                    host: https://parsoid-lb.miraheze.org
                  table:
                    backend: sqlite
                    dbname: db.sqlite3
                    pool_idle_timeout: 20000
                    retry_delay: 250
                    retry_limit: 10
                    show_sql: false
                  purged_cache_control: s-maxage=0, max-age=86400
                  purged_cache_control_client_cache: s-maxage=0, max-age=300
<%- end -%>
<%- end -%>

# Finally, a standard service-runner config.
info:
  name: restbase

logging:
  name: restbase
  level: info